name: Twitter Quote Bot

on:
  schedule:
    # Your requested times (all in UTC - adjust based on your timezone)
    - cron: '0 20 * * *'      # 1:00 AM
    - cron: '30 21 * * *'     # 2:30 AM  
    - cron: '30 1 * * *'     # 6:30 AM
    - cron: '30 3 * * *'     # 8:30 AM
    - cron: '30 10 * * *'    # 3:30 PM
    - cron: '30 18 * * *'    # 11:30 PM
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-quote-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Quote Bot
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        GOOGLE_WORKSHEET_NAME: ${{ secrets.GOOGLE_WORKSHEET_NAME }}
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python railway_quote_bot.py
